"""Lee-So (2017) 8-K filing-density z-score.

Reference: Lee, C. M. C., So, E. C. (2017). "Uncovering Expected
Returns: Information in Analyst Coverage Proxies." Journal of
Financial Economics, 124(2), 331-348.

Operational rule (per spec section 7.2 signal 5):
  For each ticker, count non-routine 8-K filings in the trailing
  `recent_window_days`. Z-score that count against the per-ticker
  same-form-type count distribution generated by rolling
  `recent_window_days`-wide windows over the trailing
  `baseline_window_days`.

  Routine items are excluded: by default items 2.02 (earnings) and
  7.01 (Reg-FD pre-announcement). The caller supplies
  ``raw_edgar_filings`` rows; we filter to form_type starting with
  '8-K' AND none of the listed items present in `item_codes`.

Sign convention: POSITIVE z == elevated information arrival. Pure
function -- no I/O, no DB, deterministic.
"""
from __future__ import annotations

import datetime as _dt
import math
from collections import defaultdict
from typing import Any


FILING_DENSITY_VERSION = "1.0"


def _parse_iso_date(s: str) -> _dt.date:
    s = str(s)
    if "T" in s:
        s = s.split("T", 1)[0]
    return _dt.date.fromisoformat(s)


def _excluded(item_codes: Any, excluded: tuple[str, ...]) -> bool:
    """Return True if any item in `item_codes` matches the excluded set.

    `item_codes` is a CSV string like '2.02,9.01' or None.
    """
    if item_codes is None:
        return False
    parts = [p.strip() for p in str(item_codes).split(",") if p.strip()]
    return any(p in excluded for p in parts)


def compute_filing_density(
    rows: list[dict[str, Any]],
    *,
    as_of_date: str,
    recent_window_days: int = 90,
    baseline_window_days: int = 365,
    excluded_8k_items: tuple[str, ...] = ("2.02", "7.01"),
) -> dict[str, float]:
    """Lee-So 2017 8-K filing-density z-score per ticker.

    Parameters
    ----------
    rows
        Per-filing rows from ``raw_edgar_filings``. Each dict has at
        minimum:
          - 'ticker': str
          - 'form_type': str (only '8-K*' counted)
          - 'filing_date': str ('YYYY-MM-DD')
          - 'item_codes': Optional[str] (CSV like '2.02,9.01')
    as_of_date
        Focal date 'YYYY-MM-DD'.
    recent_window_days
        Width of the numerator window (default 90).
    baseline_window_days
        Length of the trailing history over which to roll the
        rolling-window distribution (default 365).
    excluded_8k_items
        Item numbers to drop as routine (default '2.02', '7.01').

    Returns
    -------
    dict[str, float]
        Per-ticker z-score. NaN if the rolling baseline contains fewer
        than 30 windows.
    """
    if recent_window_days <= 0:
        raise ValueError("recent_window_days must be positive")
    if baseline_window_days <= 0:
        raise ValueError("baseline_window_days must be positive")

    as_of = _parse_iso_date(as_of_date)
    excluded_set = tuple(excluded_8k_items)

    # ticker -> sorted list of qualifying filing dates
    per_ticker: dict[str, list[_dt.date]] = defaultdict(list)
    for r in rows:
        form = str(r.get("form_type", ""))
        if not form.startswith("8-K"):
            continue
        if _excluded(r.get("item_codes"), excluded_set):
            continue
        try:
            d = _parse_iso_date(r["filing_date"])
        except (ValueError, TypeError, KeyError):
            continue
        per_ticker[r["ticker"]].append(d)

    out: dict[str, float] = {}
    for ticker, dates in per_ticker.items():
        dates.sort()
        baseline_start = as_of - _dt.timedelta(
            days=recent_window_days + baseline_window_days - 1
        )
        baseline_end = as_of - _dt.timedelta(days=recent_window_days)
        if baseline_end < baseline_start:
            out[ticker] = float("nan")
            continue

        # Window-end dates from baseline_start..baseline_end inclusive.
        # For each end-date E, count filings in [E - (W-1), E].
        n_windows = (baseline_end - baseline_start).days + 1
        if n_windows < 30:
            out[ticker] = float("nan")
            continue

        window_counts: list[int] = []
        e = baseline_start
        while e <= baseline_end:
            window_start = e - _dt.timedelta(days=recent_window_days - 1)
            cnt = sum(1 for d in dates if window_start <= d <= e)
            window_counts.append(cnt)
            e = e + _dt.timedelta(days=1)

        mu = sum(window_counts) / len(window_counts)
        var = sum((x - mu) ** 2 for x in window_counts) / len(window_counts)
        sigma = math.sqrt(var)

        # Recent count: filings in [as_of - (W-1), as_of].
        recent_start = as_of - _dt.timedelta(days=recent_window_days - 1)
        recent_cnt = sum(1 for d in dates if recent_start <= d <= as_of)

        if sigma == 0:
            out[ticker] = 0.0 if recent_cnt == mu else float("nan")
            continue
        out[ticker] = float((recent_cnt - mu) / sigma)

    return out
